jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: echo "ok d dsad sasds"
      - type: script
        script-content: echo "ok d dsad sasds"
        name: ''
  Job2:
    name: Job 2
    runs-on:
      self-hosted:
        - os-family: Mac OS
    dependencies:
      - Job1
    steps:
      - type: maven
        name: ''
        jdk-home: '%env.JDK_17_0_x64%'
  Job3:
    name: Job 3
    runs-on: Linux-Large
    steps:
      - type: script
        name: ''
        script-content: dsa d dsa
    dependencies:
      - Job1
parameters:
  param1: patam1
secrets:
  dsa: credentialsJSON:c1348059-5034-49e5-a21c-a38eb8128691
name: Amphtml
