jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: |-
          echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199
          echo "111"
          sleep 199
    runs-on: Linux-Medium
    enable-dependency-cache: true
    parameters:
      aaa: aaa
      vvvv: vvv
    output-parameters:
      rrr: rrrr
      bbbb: bbb
